%LET DT_INI = '01JAN2014'DT; /* DATA INICIAL */ 
%LET DT_FIM = '31JAN2014'DT; /* DATA FINAL */


PROC SQL;
CREATE TABLE TESTE AS SELECT
COUNT(TIPO) AS QUANT,
TIPO,
ESCOB,
BASE,
DATA_ARQUIVO
FROM ESCOBS.BDESCOB_201401 AS A
WHERE DATA_ARQUIVO >= '01JAN2014'D
AND BASE = 'REMESSA COMP'
AND ESCOB = 'A1SOLUCOES'
GROUP BY 2,3,4,5;
RUN;

PROC SQL;
CREATE TABLE TESTE AS SELECT
COUNT(TIPO) AS QUANT,
TIPO,
ESCOB,
BILLING
FROM ESCOBS.BDESCOB_201401 AS A
WHERE BASE = 'REMESSA'
AND ESCOB = 'A1SOLUCOES'
AND BILLING = "BILLING_02"	
GROUP BY 2,3,4;
RUN;

PROC SQL;
CREATE TABLE FINAL AS SELECT 	
A.*,												
B.*
FROM WORK.REMESSA AS A	LEFT JOIN WORK.BAIXA AS B					
ON A.C_ID_EMP = B.C_ID_EMP;
RUN;

PROC SQL;/*REMESSA BIILING*/
CREATE TABLE TESTE AS 
SELECT
COUNT(TIPO) AS QUANT,
TIPO,
ESCOB,
BILLING
FROM ESCOBS.BDESCOB_201401 AS A
WHERE BASE = 'REMESSA'
AND ESCOB = 'A1SOLUCOES'
AND BILLING = "BILLING_02"	
GROUP BY 2,3,4;
RUN;

PROC SQL;/*REMESSA_COMP*/
CREATE TABLE TESTE AS SELECT
COUNT(STATUS) AS QUANT,
TIPO,
ESCOB,
BASE,
DATA_ARQUIVO
FROM ESCOBS.BDESCOB_201401 AS A
WHERE BASE = 'REMESSA COMP'
AND ESCOB = 'A1SOLUCOES'
GROUP BY 2,3,4,5;
RUN;





/*************************************************************************************************/

PROC SQL;/*CRIACAO DA BASE DO BILLING*/
CREATE TABLE PRODUCAO.REMESSA_B AS SELECT
A.*
FROM ESCOBS.BDESCOB_201402 AS A
WHERE BASE = 'REMESSA';
RUN;

PROC SQL;/*CRIACAO DA BASE DIARIA*/
CREATE TABLE PRODUCAO.REMESSA_C AS SELECT
A.*
FROM ESCOBS.BDESCOB_201402 AS A
WHERE BASE = 'REMESSA COMP';
RUN;

PROC SQL;/*CRIACAO DA BASE RETIRADA*/
CREATE TABLE PRODUCAO.REMESSA_R AS SELECT
A.*
FROM ESCOBS.BDESCOB_201402 AS A
WHERE BASE = 'BAIXA';
RUN;

PROC SQL;/*CRIACAO DA BASE DE PRESTACAO*/
CREATE TABLE PRODUCAO.REMESSA_P AS SELECT
A.*
FROM ESCOBS. AS A;

RUN;





			   