/* DATA SET */
/* PARA CRIAR/REESCREVER TABELAS */

DATA SEP_13;		/* LIB.NOME_BASE - CRIAR */
SET SASUSER.EMP_SEP_QP 
SASUSER.ULT_SEP_QP
SASUSER.REMESSA_201309_EMP
SASUSER.REMESSA_201309_ULT
ULT_SEP_RETIRADA
EMP_SEP_RETIRADA;/* LIB.NOME_BASE - LEITURA */

SAFRA = "201309";
WHERE C_DLETRA = "C";
RUN;

DATA OCT_13;		/* LIB.NOME_BASE - CRIAR */
SET SASUSER.EMP_OCT_QP 
SASUSER.ULT_OCT_QP
SASUSER.A1_OCT_QP
SASUSER.REMESSA_201310_EMP
SASUSER.REMESSA_201310_ULT
SASUSER.REMESSA_201310_A1S
ULT_OCT_RETIRADA
EMP_OCT_RETIRADA
A1_OCT_RETIRADA;/* LIB.NOME_BASE - LEITURA */

SAFRA = "201310";
 WHERE C_DLETRA = "C";
RUN;

DATA NOV_13;		/* LIB.NOME_BASE - CRIAR */
 SET SASUSER.EMP_NOV_QP 
SASUSER.ULT_NOV_QP
SASUSER.A1_NOV_QP
SASUSER.REMESSA_201311_EMP
SASUSER.REMESSA_201311_ULT
SASUSER.REMESSA_201311_A1S
ULT_NOV_RETIRADA
EMP_NOV_RETIRADA
A1_NOV_RETIRADA;/* LIB.NOME_BASE - LEITURA */

SAFRA = "201311";
WHERE C_DLETRA = "C";
RUN;

/* DATA SET */
/* PARA CRIAR/REESCREVER TABELAS */

DATA ESCOBS.BDESCOB2013;		/* LIB.NOME_BASE - CRIAR */
SET SEP_13
OCT_13
NOV_13;		/* LIB.NOME_BASE - LEITURA */
FORMAT MISDATE DATE10.;

	 IF P_COBR = "00035" THEN ESCOB = "A1SOLUCOES            ";
ELSE IF P_COBR = "00032" THEN ESCOB = "ULTRACENTER";
ELSE IF P_COBR = "00031" THEN ESCOB = "EMPRESARIO";
	 
	 IF P_SITUAC = "ENV" THEN STATUS = "REMESSA    ";
ELSE IF P_SITUAC = "BXA" AND C_MOTIVO_BXA = "DP" THEN STATUS = "DECURSO";
ELSE IF P_SITUAC = "BXA" AND C_MOTIVO_BXA = "PG" THEN STATUS = "PAGAMENTO";
ELSE IF P_SITUAC = "BXA" AND C_MOTIVO_BXA = "OT" THEN STATUS = "OUTROS";
ELSE STATUS = "XXX";

ESPECIE = SUBSTR(C_NUMT,7,2);
TITULO = SUBSTR(C_NUMT,9,10) ;
ANO_VENC = SUBSTR(C_DATEMI,1,4);
BILLING = "BILLING_"||SUBSTR(C_VENCIM,7,2);
MISDATE = TODAY();

IF LENGTH(C_CODI) = 14 THEN TIPO = "PJ";
ELSE TIPO = "PF"; 

DATA_REMESSA = SUBSTR(C_VENCIM,7,2)||"/"||SUBSTR(C_VENCIM,5,2)||"/"||SUBSTR(C_VENCIM,1,4);

RUN;

/* DATA SET */
/* PARA CRIAR/REESCREVER TABELAS */

DATA SEP_PC;		/* LIB.NOME_BASE - CRIAR */
SET ULT_SEP_PC
EMP_SEP_PC;

SAFRA = "201309";/* LIB.NOME_BASE - LEITURA */
RUN;

/* DATA SET */
/* PARA CRIAR/REESCREVER TABELAS */

DATA OCT_PC;		/* LIB.NOME_BASE - CRIAR */
SET ULT_OCT_PC
EMP_OCT_PC
A1_OCT_PC;

SAFRA = "201310";/* LIB.NOME_BASE - LEITURA */
RUN;

DATA NOV_PC;		/* LIB.NOME_BASE - CRIAR */
SET ULT_NOV_PC EMP_NOV_PC A1_NOV_PC;

SAFRA = "201311";/* LIB.NOME_BASE - LEITURA */
RUN;


DATA ESCOBS.BDPRESTACAO2013 (DROP= P_DEMI P_NUMT P_CODI);		/* LIB.NOME_BASE - CRIAR */
SET SEP_PC OCT_PC NOV_PC;		/* LIB.NOME_BASE - LEITURA */

C_DATEMI = P_DEMI;
C_NUMT = P_NUMT;
C_CODI = P_CODI;
MISDATE = TODAY();
FORMAT MISDATE DATE10.;

	 IF P_COBR = "00035" THEN ESCOB = "A1SOLUCOES            ";
ELSE IF P_COBR = "00032" THEN ESCOB = "ULTRACENTER";
ELSE IF P_COBR = "00031" THEN ESCOB = "EMPRESARIO";
	 
STATUS = "PRESTACAO";

ESPECIE = SUBSTR(C_NUMT,7,2);
TITULO = SUBSTR(C_NUMT,9,10) ;
ANO_VENC = SUBSTR(C_DATEMI,1,4);
BILLING = "BILLING_"||SUBSTR(P_VENCIM,7,2);

IF LENGTH(C_CODI) = 14 THEN TIPO = "PJ";
ELSE TIPO = "PF"; 

IF 	P_SITUAC = "BXA" THEN  VENC_TIT = SUBSTR(P_DEMI,7,2)||"/"||SUBSTR(P_DEMI,5,2)||SUBSTR(P_DEMI,1,4);
ELSE VENC_TIT = SUBSTR(P_VENCIM,7,2)||"/"||SUBSTR(P_VENCIM,5,2)||"/"||SUBSTR(P_VENCIM,1,4);

IF 	P_SITUAC = "BXA" THEN MES_VENC_TIT = SUBSTR(P_DEMI,5,2)||SUBSTR(P_DEMI,1,4);
ELSE MES_VENC_TIT = SUBSTR(P_VENCIM,5,2)||"/"||SUBSTR(P_VENCIM,1,4);

VALOR = P_VLRPRI*1;

DATA_PC = SUBSTR(P_DPGDEV,7,2)||"/"||SUBSTR(P_DPGDEV,5,2)||"/"||SUBSTR(P_DPGDEV,1,4);

RUN;






